//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyplom_Rozhko_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        public int OrderDetailsId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsCanceled { get; set; }

        [Required(ErrorMessage = "Заповніть поле")]
        public string City { get; set; }

        [Required(ErrorMessage = "Заповніть поле")]
        public string DeliveryMethod { get; set; }

        [Required(ErrorMessage = "Заповніть поле")]
        public Nullable<int> DepartmentNumber { get; set; }

        [Required(ErrorMessage = "Заповніть поле")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Заповніть поле")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Заповніть поле")]
        public string PaymentMethod { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
